version: '2.4'

services:

  data-exploration:
    image: tensorflow/tensorflow:1.13.1-py3-jupyter
    init: true

    ports:
      - 8888:8888
      - 6006:6006

    volumes:
      - ./data:/data
      - ./notebooks:/notebooks

    working_dir: /notebooks

    command: jupyter notebook --allow-root --ip 0.0.0.0 --NotebookApp.custom_display_url=http://localhost:8888
  
  augment-images:
    build: .
    runtime: nvidia

    volumes: 
      - ./:/code
      -  ./data:/data
      - ./models:/models

    working_dir: /code

    ports:
      - 6006:6006

    stdin_open: true
    tty: true

    command: bash pilotnet/scripts/data-augmentation.sh

  
